// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AddTaskDialog: typeof import('./src/components/dialogs/AddTaskDialog.vue')['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Brain: typeof import('./src/components/Icons/Brain.vue')['default']
    CategorySelect: typeof import('./src/components/molecules/CategorySelect.vue')['default']
    Chip: typeof import('./src/components/atoms/Chip.vue')['default']
    DetailsSection: typeof import('./src/components/organism/DetailsSection.vue')['default']
    EffortChips: typeof import('./src/components/molecules/EffortChips.vue')['default']
    EffortScale: typeof import('./src/components/molecules/EffortScale.vue')['default']
    EffortSection: typeof import('./src/components/organism/EffortSection.vue')['default']
    Header: typeof import('./src/components/organism/Header.vue')['default']
    Hint: typeof import('./src/components/atoms/Hint.vue')['default']
    HintText: typeof import('./src/components/atoms/HintText.vue')['default']
    HomeView: typeof import('./src/components/views/HomeView.vue')['default']
    Input: typeof import('./src/components/atoms/Input.vue')['default']
    Label: typeof import('./src/components/atoms/Label.vue')['default']
    List: typeof import('./src/components/molecules/List.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    RepeaterSelect: typeof import('./src/components/molecules/RepeaterSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScheduledTask: typeof import('./src/components/organism/ScheduledTask.vue')['default']
    SelectCategories: typeof import('./src/components/organism/SelectCategories.vue')['default']
    SliderNav: typeof import('./src/components/organism/SliderNav.vue')['default']
    StyledDatePicker: typeof import('./src/components/molecules/StyledDatePicker.vue')['default']
    StyledDatePicket: typeof import('./src/components/molecules/StyledDatePicket.vue')['default']
    StyledInput: typeof import('./src/components/molecules/StyledInput.vue')['default']
    StyledTextArea: typeof import('./src/components/molecules/StyledTextArea.vue')['default']
    TotalRubies: typeof import('./src/components/organism/TotalRubies.vue')['default']
  }
}
